# MAKİNE ÖĞRENMESİ

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("veriseti.csv")

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
df.info

<bound method DataFrame.info of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL 

In [5]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [7]:
df.shape

(7043, 21)

In [8]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

Genellikle obje ve bir kaç numeric değerler var

In [10]:
df.TotalCharges= pd.to_numeric(df.TotalCharges, errors="coerce") #Total charges i sayılsa veriye çevirdik

In [11]:
#Eksik veri kontrolü
df.isnull().sum()


customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [12]:
#Yalnızca Total Charge değeri 11 null içeriyor. Sıfır atayalım.
df.TotalCharges= df.TotalCharges.fillna(0)

In [13]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [14]:
df.isnull().sum().sum()

0

Verisetimizin sütun isimlerini düzenleme işlemini yapalım.

In [16]:
df.columns= df.columns.str.lower().str.replace(" ", "_") #Hepsini küçük ve boşlukara _ koyduk

In [17]:
string_columns= list(df.dtypes[df.dtypes=="object"].index)

In [18]:
string_columns

['customerid',
 'gender',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'churn']

For döngüsüyle obje değerli sütunların değerlerinin hepsini küçük harfe çevirip ardından boşluklara _ verelim.

In [19]:
for col in string_columns:
    df[col]=df[col].str.lower().str.replace(" ","_")

In [20]:
df.head()

customerid  gender  seniorcitizen partner dependents  tenure phoneservice  \
0  7590-vhveg  female              0     yes         no       1           no   
1  5575-gnvde    male              0      no         no      34          yes   
2  3668-qpybk    male              0      no         no       2          yes   
3  7795-cfocw    male              0      no         no      45           no   
4  9237-hqitu  female              0      no         no       2          yes   

      multiplelines internetservice onlinesecurity  ... deviceprotection  \
0  no_phone_service             dsl             no  ...               no   
1                no             dsl            yes  ...              yes   
2                no             dsl            yes  ...               no   
3  no_phone_service             dsl            yes  ...              yes   
4                no     fiber_optic             no  ...               no   

  techsupport streamingtv streamingmovies        contract paperlessbilling  \
0          no          no              no  month-to-month              yes   
1          no          no              no        one_year               no   
2          no          no              no  month-to-month              yes   
3         yes          no              no        one_year               no   
4          no          no              no  month-to-month              yes   

               paymentmethod monthlycharges  totalcharges  churn  
0           electronic_check          29.85         29.85     no  
1               mailed_check          56.95       1889.50     no  
2               mailed_check          53.85        108.15    yes  
3  bank_transfer_(automatic)          42.30       1840.75     no  
4           electronic_check          70.70        151.65    yes  

[5 rows x 21 columns]

In [21]:
#hedef değişkenin değerlerine bakalım

df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: object

In [22]:
#Yes lere 1 no lara 0 atayalım
df.churn= (df.churn == "yes").astype(int)

In [23]:
df.churn.head()

0    0
1    0
2    1
3    0
4    1
Name: churn, dtype: int32

# VERİ SETİNİ PARÇALAMA

Train verisiyle model kurulur, test verisiyle test edilir.

In [24]:
from sklearn.model_selection import train_test_split

In [27]:
# df_train_full, df_test= train_test_split(df,test_size=0.2, random_state=42)

In [28]:
df_train, df_val= train_test_split(df_train_full,test_size=0.25, random_state=42)

# HEDEF DEĞİŞKEN VE ÖZNİTELİKLER

In [29]:
y_train= df_train.churn.values

In [30]:
y_val= df_val.churn.values

Hedef sütunun veri setinden sileceğiz

In [31]:
del df_train["churn"]
del df_val["churn"]

# ÖZNİTELİK MÜHENDİSLİĞİ

In [34]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',  
               'phoneservice', 'multiplelines', 'internetservice',  
               'onlinesecurity', 'onlinebackup', 'deviceprotection',  
               'techsupport', 'streamingtv', 'streamingmovies',  'contract', 
               'paperlessbilling', 'paymentmethod']

In [35]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [38]:
train_dict= df_train[categorical+numerical ].to_dict(orient= "records")

In [41]:
train_dict[1]

{'gender': 'female',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'yes',
 'phoneservice': 'yes',
 'multiplelines': 'no',
 'internetservice': 'fiber_optic',
 'onlinesecurity': 'no',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'yes',
 'streamingtv': 'yes',
 'streamingmovies': 'yes',
 'contract': 'one_year',
 'paperlessbilling': 'yes',
 'paymentmethod': 'bank_transfer_(automatic)',
 'tenure': 55,
 'monthlycharges': 103.7,
 'totalcharges': 5656.75}

Kategorik verileri oneHot kodlamaya çevirelim. Yani sözel olan değerlerimizi birer sayısal değere çevirme işlemi.

One-hot kodlama, verileri temsil etmek için sıklıkla kullanılan bir yöntemdir. Bu yöntem, verileri bir dizi veya matris şeklinde ifade ederek, her bir öğeyi sadece 0 veya 1 değerleriyle temsil etme şeklidir.

Bu yöntemde, verilerdeki her öğe için ayrı bir sütun veya boyut atanır ve bu sütunun değeri o öğeye ait olup olmadığına göre 0 veya 1 olarak belirlenir. Bu nedenle, herhangi bir veri noktası sadece bir sütunda 1 değerine sahip olabilir ve diğer tüm sütunlarında 0 değerine sahip olur.

Örneğin, bir meyve listesi düşünelim: elma, armut, çilek. Bu listeyi one-hot encoding yöntemiyle ifade etmek için, her meyve için bir sütun belirlenir ve sütun değerleri aşağıdaki gibi atanır:

elma: [1, 0, 0]
armut: [0, 1, 0]
çilek: [0, 0, 1]

Bu şekilde, her bir meyve sadece kendi sütununda 1 değerine sahip olur ve diğer tüm sütunlarda 0 değerine sahip olur.

In [42]:
from sklearn.feature_extraction import DictVectorizer

Dict Vectorizer sınıfından bir örnek alalım.

In [43]:
dv= DictVectorizer(sparse= False) #sparse=False numpy dizisi şeklinde olmasını istediğimiz için

Aldığımız örneği verisetine göre eğittk.

In [47]:
dv.fit(train_dict)

DictVectorizer(sparse=False)

Eğittiğimzi bu örneğe göre eğitim verisini dönüştürelim.

In [50]:
x_train=dv.transform(train_dict)

In [51]:
x_train[0]

array([ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,
        1.  ,  0.  ,  0.  ,  1.  , 19.85,  1.  ,  0.  ,  0.  ,  0.  ,
        1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,
        0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  3.  , 64.55])

Sutunların değerlerin get_features_names_out methodu ile görebiliriz. 

In [53]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',

# MODEL kURMA

In [54]:
from sklearn.linear_model import LogisticRegression

In [56]:
model= LogisticRegression(solver="liblinear", random_state= 42)

In [57]:
model.fit(x_train, y_train)

LogisticRegression(random_state=42, solver='liblinear')

Modelin peformansını ölçebilmek için validasyon verisini kullanırız. 



# MODEL DEĞERLENDİRME

In [58]:
val_dict= df_val[categorical+ numerical].to_dict(orient="records")

In [61]:
x_val=dv.transform(val_dict)

In [62]:
y_pred=model.predict_proba(x_val)


In [63]:
y_pred[:5]

array([[0.83279835, 0.16720165],
       [0.74686665, 0.25313335],
       [0.56434035, 0.43565965],
       [0.43763419, 0.56236581],
       [0.95025839, 0.04974161]])

In [64]:
model.score(x_val, y_val)

0.8034066713981547

In [65]:
model.score(x_train, y_train)

0.8049704142011834

İyi bir modelin validasyon ve eğitim verileri üzerindeki modelin doğruluklarının birbirine ve 1 e yakın olmasını yakın olmasını isteriz.

# MODEL YORUMLAMA

Kurduğumuz modelde her bir değişkenin bir katsayısı bir de sabit terimi vardır. Biz en optimize katsayı kombinasyonunu bulmak istiyoruz.

In [66]:
#sabit terimi görelim
model.intercept_[0]

-0.14501410816342655

In [70]:
#Her bir sütunun katsayılarını ekrana yazdırmak istersek 
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'contract=month-to-month': 0.63,
 'contract=one_year': -0.16,
 'contract=two_year': -0.615,
 'dependents=no': -0.054,
 'dependents=yes': -0.091,
 'deviceprotection=no': 0.027,
 'deviceprotection=no_internet_service': -0.132,
 'deviceprotection=yes': -0.04,
 'gender=female': 0.015,
 'gender=male': -0.16,
 'internetservice=dsl': -0.327,
 'internetservice=fiber_optic': 0.314,
 'internetservice=no': -0.132,
 'monthlycharges': 0.003,
 'multiplelines=no': -0.225,
 'multiplelines=no_phone_service': 0.124,
 'multiplelines=yes': -0.044,
 'onlinebackup=no': 0.076,
 'onlinebackup=no_internet_service': -0.132,
 'onlinebackup=yes': -0.089,
 'onlinesecurity=no': 0.205,
 'onlinesecurity=no_internet_service': -0.132,
 'onlinesecurity=yes': -0.217,
 'paperlessbilling=no': -0.241,
 'paperlessbilling=yes': 0.096,
 'partner=no': -0.076,
 'partner=yes': -0.069,
 'paymentmethod=bank_transfer_(automatic)': -0.107,
 'paymentmethod=credit_card_(automatic)': -0.186,
 'paymentmethod=electronic_check': 0.211,
 '

İncelersek bazı katsayıların negatif bazılarının pozitif olduğunu görmekteyiz. Demek ki negatif katsayıların hedef değişkeni ile  ters orantılı olduğunu ve pozitif katsayıların sahip olduğu sütunlarımız ise doğru orantılır.

# YENİ VERİYİ TAHMİN ETME

Bunu tahin edebilmek için bir müşterinin değerlerini alalım

In [71]:
customer = {
 'customerid': '8879-zkjof',
 'gender': 'male',
 'seniorcitizen': 1,
 'partner': 'no',
 'dependents': 'no',
 'tenure': 41,
 'phoneservice': 'yes',
 'multiplelines': 'no',
 'internetservice': 'dsl',
 'onlinesecurity': 'yes',
 'onlinebackup': 'no',
 'deviceprotection': 'yes',
 'techsupport': 'yes',
 'streamingtv': 'yes',
 'streamingmovies': 'yes',
 'contract': 'one_year',
 'paperlessbilling': 'yes',
 'paymentmethod': 'bank_transfer_(automatic)',
 'monthlycharges': 79.85,
 'totalcharges': 2990.75,
}

Yukarıdaki veri ham veri öncelikle bu veriyi model kurarken kullandığımız hale getirmemiz gerekiyor.

In [72]:
x_new= dv.transform([customer])

In [74]:
model.predict_proba(x_new) #Bu müşterinin abonelikten çıkma olasılığı düşüktür.

array([[0.93840224, 0.06159776]])

In [75]:
customer2 = {
 'gender': 'female',
 'seniorcitizen': 1,
 'partner': 'no',
 'dependents': 'no',
 'phoneservice': 'yes',
 'multiplelines': 'yes',
 'internetservice': 'fiber_optic',
 'onlinesecurity': 'no',
 'onlinebackup': 'no',
 'deviceprotection': 'no',
 'techsupport': 'no',
 'streamingtv': 'yes',
 'streamingmovies': 'no',
 'contract': 'month-to-month',
 'paperlessbilling': 'yes',
 'paymentmethod': 'electronic_check',
 'tenure': 1,
 'monthlycharges': 85.7,
 'totalcharges': 85.7
}

In [76]:
x_new2 = dv.transform([customer2])  #Çıkan sonuçlara göre bu müşterinin ayrılma ihtimali %80
model.predict_proba(x_new2)

array([[0.19738625, 0.80261375]])